// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "通过用户名密码登录（MongoDB），成功后设置 HttpOnly Cookie 并将 Session 写入 Redis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录凭据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok=true, user=AuthUser",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "description": "清除 Session Cookie 和 Redis 中的 Session 记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "ok=true",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/session": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "通过 Cookie 或 Bearer Token 获取当前登录用户信息（需认证）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取当前会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "taishan_session=xxx",
                        "name": "Cookie",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Bearer xxx",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "401": {
                        "description": "error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "检查 PostgreSQL、Redis 和 MongoDB 连接状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/model.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/system/info": {
            "get": {
                "description": "获取服务版本、Go 版本、启动时间等信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "系统信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SystemInfo"
                        }
                    }
                }
            }
        },
        "/api/wecom/kefu-customers": {
            "get": {
                "description": "返回所有客服客户，包含消息统计和最后活跃时间",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "企业微信"
                ],
                "summary": "客服客户列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.KefuCustomer"
                            }
                        }
                    }
                }
            }
        },
        "/api/wecom/kefu-messages": {
            "get": {
                "description": "根据 external_userid 查询微信客服消息，包含用户提问（received）和机器人回复（sent），支持时间范围筛选",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "企业微信"
                ],
                "summary": "查询客服聊天记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "外部用户ID",
                        "name": "external_userid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始时间（RFC3339 格式，如 2026-05-01T00:00:00Z）",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "截止时间（RFC3339 格式）",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "返回条数（最大 500）",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.KefuMessage"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/wecom/messages": {
            "get": {
                "description": "根据企业微信 platform_user_id 查询该用户相关的所有消息（作为发送者或接收者），支持时间范围和会话类型筛选",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "企业微信"
                ],
                "summary": "查询用户聊天记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "企业微信用户ID（如 GuoTongJia）",
                        "name": "platform_user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "MongoDB 公司 ID（可选，不传则不过滤公司）",
                        "name": "company_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "起始时间（毫秒时间戳）",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "截止时间（毫秒时间戳）",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "all",
                        "description": "会话类型：all / group / private",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "返回条数（最大 500）",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.WecomMessage"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.HealthResponse": {
            "type": "object",
            "properties": {
                "mongo": {
                    "type": "string"
                },
                "postgres": {
                    "type": "string"
                },
                "redis": {
                    "type": "string"
                }
            }
        },
        "model.KefuCustomer": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "externalUserId": {
                    "type": "string"
                },
                "lastActiveAt": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "totalReceived": {
                    "type": "integer"
                },
                "totalSent": {
                    "type": "integer"
                }
            }
        },
        "model.KefuMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                },
                "externalUserId": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "messageId": {
                    "type": "string"
                },
                "msgType": {
                    "type": "string"
                },
                "openKfId": {
                    "type": "string"
                }
            }
        },
        "model.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.SystemInfo": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string"
                },
                "goVersion": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "companyId": {
                    "type": "integer"
                },
                "companyName": {
                    "type": "string"
                },
                "dataScope": {
                    "type": "integer"
                },
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "realName": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.WecomMessage": {
            "type": "object",
            "properties": {
                "chatId": {
                    "type": "string"
                },
                "chatName": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "createTime": {
                    "type": "integer"
                },
                "direction": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "messageId": {
                    "type": "string"
                },
                "msgType": {
                    "type": "string"
                },
                "receiveId": {
                    "type": "string"
                },
                "receiveIdType": {
                    "type": "string"
                },
                "senderId": {
                    "type": "string"
                },
                "senderIdType": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:4007",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TaishanXD V2 API",
	Description:      "销售赋能中心后端 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
