-- TaishanXD V2 Schema
-- Core RBAC tables + bootstrap data

-- ── Companies ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS companies (
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── Departments ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS departments (
    id          SERIAL PRIMARY KEY,
    company_id  INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    parent_id   INTEGER DEFAULT 0,
    dept_name   VARCHAR(100) NOT NULL,
    tree_path   TEXT NOT NULL,
    sort_order  INTEGER DEFAULT 0,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_dept_tree_path ON departments (tree_path text_pattern_ops);
CREATE INDEX IF NOT EXISTS idx_dept_company ON departments (company_id);

-- ── Users ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id              SERIAL PRIMARY KEY,
    company_id      INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    dept_id         INTEGER REFERENCES departments(id) ON DELETE SET NULL,
    username        VARCHAR(50) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    real_name       VARCHAR(50),
    is_active       BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_company_username ON users (company_id, username);
CREATE INDEX IF NOT EXISTS idx_users_dept ON users (dept_id);

-- ── Roles ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS roles (
    id          SERIAL PRIMARY KEY,
    company_id  INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    role_name   VARCHAR(50) NOT NULL,
    data_scope  SMALLINT NOT NULL DEFAULT 4,
    description TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── User-Roles mapping ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_roles (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON user_roles (role_id);

-- ── Company-Apps mapping ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS company_apps (
    company_id INTEGER NOT NULL REFERENCES companies(id),
    app_id     VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (company_id, app_id)
);

-- ── Bootstrap: seed admin account ─────────────────────────────
-- Password: admin123 (scrypt hash generated by Go crypto script)
-- For demo we use a simple bcrypt-compatible hash

INSERT INTO companies (name) VALUES ('泰山销售赋能中心') ON CONFLICT DO NOTHING;
INSERT INTO departments (company_id, parent_id, dept_name, tree_path, sort_order)
    VALUES (1, 0, '总经办', '0/1/', 0) ON CONFLICT DO NOTHING;
INSERT INTO roles (company_id, role_name, data_scope, description)
    VALUES (1, '超级管理员', 1, '公司级全部数据权限') ON CONFLICT DO NOTHING;
